
import type { MonthData } from './events-data';

export const WWF_ALL_DATA: MonthData[] = [
  {
    month: 'Enero',
    monthId: 'january',
    year: 2000,
    raw: [
      { date: '3', location: 'Miami, FL', description: 'Triple H, ahora campeón, consolida su poder con Stephanie McMahon.', matches: ['The Dudley Boyz (Bubba Ray & D-Von Dudley) vs. Too Cool (Scotty 2 Hotty & Grandmaster Sexay)', 'Kurt Angle vs. Kane', 'Chyna vs. Hardcore Holly (Campeonato Intercontinental de la WWF)', 'Triple H vs. Big Show (Campeonato de la WWF)', 'Big Boss Man & Prince Albert vs. Test, The Fabulous Moolah & Mae Young (Handicap 3 vs. 2)', 'The Acolytes (Bradshaw & Faarooq) vs. The Mean Street Posse (Joey Abs, Pete Gas & Rodney) (Handicap 3 vs. 2)', 'Jeff Hardy vs. Al Snow (Jaula de acero)', 'The Rock vs. D-Generation X (X-Pac & The New Age Outlaws (Road Dogg & Billy Gunn)) (No DQ, Handicap 3 vs. 1; Si Rock pierde, es despedido)'] },
      { date: '10', location: 'St. Louis, MO', description: 'The Rock regresa y gana una batalla real para ser retador en Royal Rumble.', matches: ['Road Dogg vs. Billy Gunn', 'The Hardy Boyz (Matt & Jeff Hardy) vs. Kurt Angle & Steve Blackman', 'Val Venis vs. Edge (Campeonato Europeo de la WWF)', 'The Hollys (Hardcore & Crash Holly) vs. Chris Jericho & Chyna', 'Triple H vs. X-Pac (Campeonato de la WWF)', 'Too Cool (Scotty 2 Hotty & Grandmaster Sexay) & Rikishi vs. The Headbangers (Mosh & Thrasher) & Al Snow', 'The Dudley Boyz (Bubba Ray & D-Von Dudley) vs. The Godfather & D\'Lo Brown', 'Big Show & Test vs. Big Boss Man & Prince Albert', 'D-Generation X (Triple H, X-Pac & The New Age Outlaws (Road Dogg & Billy Gunn)) vs. The Rock \'n\' Sock Connection (The Rock & Mankind) & The Acolytes (Bradshaw & Faarooq)'] },
      { date: '17', location: 'New Haven, CT', description: 'La facción McMahon-Helmsley domina, pactando luchas injustas.', matches: ['Test vs. Big Boss Man (Campeonato Hardcore de la WWF)', 'D\'Lo Brown & The Godfather vs. Edge & Christian', 'Kurt Angle vs. Steve Blackman', 'The Acolytes (Bradshaw & Faarooq) vs. D-Generation X (Triple H & X-Pac)', 'Jeff Hardy vs. Bubba Ray Dudley', 'Rikishi vs. Chris Jericho (Campeonato Intercontinental de la WWF)', 'Kane vs. Prince Albert', 'The New Age Outlaws (Road Dogg & Billy Gunn) vs. The Rock \'n\' Sock Connection (The Rock & Mankind)'] },
      { date: '24', location: 'El Paso, TX', description: 'La noche después del Rumble. Cactus Jack emerge como el nuevo retador de Triple H.', matches: ['Al Snow & Steve Blackman vs. Edge & Christian', 'Chris Jericho vs. Hardcore Holly (Campeonato Intercontinental de la WWF)', 'Viscera & Crash Holly vs. Too Cool (Scotty 2 Hotty & Grandmaster Sexay)', 'Kane vs. X-Pac', 'The Hardy Boyz (Matt & Jeff Hardy) vs. The New Age Outlaws (Road Dogg & Billy Gunn) (Campeonatos en Parejas de la WWF)', 'The Acolytes (Bradshaw & Faarooq) vs. The Godfather & D\'Lo Brown', 'Big Boss Man vs. Test', 'The Rock & Rikishi vs. Triple H & Big Show'] },
      { date: '31', location: 'Lafayette, LA', description: 'The Radicalz (Benoit, Guerrero, Saturn, Malenko) debutan desde WCW.', matches: ['The New Age Outlaws (Road Dogg & Billy Gunn) vs. Al Snow & Steve Blackman (Campeonatos en Parejas de la WWF)', 'Christian vs. D-Von Dudley', 'Big Show vs. Too Cool (Scotty 2 Hotty & Grandmaster Sexay) (Handicap 2 vs. 1)', 'The Rock vs. Kurt Angle', 'X-Pac vs. Chris Jericho', 'Hervina vs. The Kat (Campeonato Femenino de la WWF - Lucha Lumberjill Snow Bunny)', 'The Hollys (Hardcore & Crash Holly) vs. Viscera (Handicap 2 vs. 1)', 'Bubba Ray Dudley vs. Matt Hardy', 'Triple H vs. Kane (Campeonato de la WWF)'] },
    ],
    smackdown: [
      { date: '6', location: 'Orlando, FL', description: 'X-Pac y Big Show se enfrentan en el evento principal.', matches: ['X-Pac vs. Big Show', 'The Hollys (Hardcore Holly & Crash Holly) vs. Chris Jericho & Chyna', 'The Acolytes (John Layfield & Ron Simmons) vs. Billy Gunn (Handicap 2 vs. 1)', 'Kane vs. Road Dogg', 'Kurt Angle vs. The Rock', 'Edge, Christian & Jeff Hardy vs. The Dudley Boyz (Bubba Ray & D-Von Dudley) & Al Snow', 'Test vs. Big Boss Man', 'Kaientai (Taka Michinoku & Funaki) vs. The Mean Street Posse (Joey Abs, Rodney & Pete Gas) (Handicap 3 vs. 2)', 'Rikishi vs. Triple H (Campeonato de la WWF)'] },
      { date: '13', location: 'Chicago, IL', description: 'Triple H y The Rock se enfrentan en un combate de parejas.', matches: ['The New Age Outlaws (Road Dogg & Billy Gunn) vs. John Layfield (Handicap 2 vs. 1)', 'Too Cool (Scotty 2 Hotty & Grandmaster Sexay) & Rikishi vs. The Hollys (Hardcore Holly & Crash Holly) & Al Snow', 'Test vs. Gangrel', 'The Hardy Boyz (Matt Hardy & Jeff Hardy) vs. Big Boss Man & Prince Albert', 'Edge & Christian vs. Kurt Angle & Steve Blackman', 'The New Age Outlaws (Road Dogg & Billy Gunn) vs. Ron Simmons (Handicap 2 vs. 1)', 'The Godfather & D\'Lo Brown vs. The Headbangers (Mosh & Thrasher)', 'Kane vs. Chris Jericho', 'Triple H & X-Pac vs. The Rock & Big Show'] },
      { date: '20', location: 'Providence, RI', description: 'X-Pac gana una oportunidad clave para Royal Rumble.', matches: ['X-Pac vs. Test (Ganador obtiene el puesto #30 en el Royal Rumble)', 'Al Snow & Steve Blackman vs. Kurt Angle & The British Bulldog', 'Matt Hardy vs. D-Von Dudley', 'Prince Albert vs. Big Boss Man', 'Too Cool (Scotty 2 Hotty & Grandmaster Sexay) & Rikishi vs. Chris Jericho, Hardcore Holly & Chyna', 'Viscera vs. Crash Holly', 'Gangrel vs. Edge', 'Kane vs. Big Show & The Rock (Lumberjack Over the Top Rope Challenge)'] },
      { date: '27', location: 'Baltimore, MD', description: 'Cactus Jack ataca a Triple H, construyendo su lucha para No Way Out.', matches: ['Al Snow vs. Billy Gunn (Si Snow gana, él y Steve Blackman obtienen una oportunidad por los Campeonatos en Parejas de la WWF)', 'Edge & Christian vs. The Dudley Boyz (Bubba Ray & D-Von Dudley)', 'Viscera vs. Hardcore Holly', 'The Godfather & D\'Lo Brown vs. Too Cool (Scotty 2 Hotty & Grandmaster Sexay)', 'Test vs. Gangrel (Campeonato Hardcore de la WWF)', 'Tazz vs. The Mean Street Posse (Joey Abs, Rodney & Pete Gas) (Handicap 3 vs. 1)', 'Chris Jericho vs. Crash Holly (Campeonato Intercontinental de la WWF)', 'The Rock vs. Rikishi'] },
    ],
    ppvs: [
      { date: '23', name: 'Royal Rumble', location: 'New York, NY', description: 'The Rock gana el Royal Rumble Match. Triple H retiene el título contra Cactus Jack en una brutal Street Fight.', matches: ['Tazz vs. Kurt Angle', {match: 'The Hardy Boyz (Jeff Hardy y Matt Hardy) vs. The Dudley Boyz (Bubba Ray Dudley y D-Von Dudley)', rating: 3.8}, 'Chris Jericho vs. Chyna vs. Hardcore Holly (Campeonato Intercontinental de la WWF)', 'The New Age Outlaws (Billy Gunn y Road Dogg) vs. The Acolytes (Bradshaw y Faarooq) (Campeonatos en Parejas de la WWF)', {match: 'Triple H vs. Cactus Jack (Street Fight por el Campeonato de la WWF)', rating: 4.8}, {match: 'Royal Rumble de 30 hombres', rating: 3.5}], coverUrl: 'https://upload.wikimedia.org/wikipedia/en/b/bb/Royal_Rumble_2000.jpg' },
    ],
  },
  {
    month: 'Febrero',
    monthId: 'february',
    year: 2000,
    raw: [
      { date: '7', location: 'Dallas, TX', matches: ['The New Age Outlaws (Road Dogg & Billy Gunn) © vs. Edge & Christian (Campeonatos en Parejas de la WWF)', 'Kurt Angle vs. Mark Henry', 'The Hollys (Hardcore Holly & Crash Holly) vs. The Acolytes (Bradshaw & Faarooq) (Lucha hardcore en parejas)', 'Chris Jericho © vs. Viscera (Campeonato Intercontinental de la WWF)', 'Jacqueline © vs. Luna Vachon (Campeonato Femenino de la WWF)', 'The Dudley Boyz (Bubba Ray & D-Von Dudley) vs. The Godfather & D\'Lo Brown', 'Chris Benoit, Dean Malenko, Perry Saturn, Triple H & X-Pac vs. Cactus Jack, The Rock, Rikishi & Too Cool (Scotty 2 Hotty & Grandmaster Sexay) (Lucha en equipo de 10 hombres)'] },
      { date: '14', location: 'San Jose, CA', matches: ['D-Von Dudley vs. Edge vs. Jeff Hardy (Triple amenaza por la candidatura #1 a los Campeonatos en Parejas de la WWF)', 'Grandmaster Sexay vs. Road Dogg', 'Scotty 2 Hotty vs. Billy Gunn', 'Essa Rios © vs. Crash Holly (Campeonato Ligero de la WWF)', 'Tazz vs. Hardcore Holly', 'Rikishi vs. Dean Malenko & Perry Saturn (Handicap 2 vs. 1)', 'Chris Benoit vs. The Rock', 'Kane, Cactus Jack & The Rock vs. Triple H, Big Show & X-Pac'] },
      { date: '21', location: 'Atlanta, GA', matches: ['Kurt Angle & The British Bulldog vs. Chris Jericho & Chyna', 'Too Cool (Scotty 2 Hotty & Grandmaster Sexay) vs. Al Snow & Steve Blackman', 'Perry Saturn & Dean Malenko vs. D\'Lo Brown & The Godfather', 'Edge, Christian & The Hardy Boyz (Matt Hardy & Jeff Hardy) vs. The New Age Outlaws (Road Dogg & Billy Gunn) & The Dudley Boyz (Bubba Ray & D-Von Dudley)', 'The Acolytes (Bradshaw & Faarooq) & Mark Henry vs. The Hollys (Hardcore Holly & Crash Holly) & Viscera', 'Chris Benoit vs. Test', 'Rikishi vs. Eddie Guerrero', 'Tazz vs. Big Boss Man', 'Triple H ©, Big Show & X-Pac vs. The Rock, Cactus Jack & Kane (Campeonato de la WWF)'] },
      { date: '28', location: 'Nueva York, NY', matches: ['The Hardy Boyz (Matt Hardy & Jeff Hardy) vs. The Acolytes (Bradshaw & Faarooq)', 'Edge & Christian vs. Al Snow & Steve Blackman', 'Rikishi vs. Kurt Angle © (Campeonato Europeo de la WWF)', 'The Rock vs. Big Show & Triple H (Handicap 2 vs. 1)', 'Crash Holly © vs. Mark Henry (Campeonato Hardcore de la WWF)', 'Tazz vs. Prince Albert', 'Too Cool (Scotty 2 Hotty & Grandmaster Sexay) vs. The Headbangers (Mosh & Thrasher)'] },
    ],
    smackdown: [
      { date: '3', location: 'El Paso, TX', description: 'Si The Radicalz ganan 2 de 3 luchas, obtienen contratos con la WWF.', matches: ['Dean Malenko vs. X-Pac', 'Perry Saturn & Eddie Guerrero vs. The New Age Outlaws (Road Dogg & Billy Gunn) © (Campeonatos en Parejas de la WWF)', 'Triple H © vs. Chris Benoit (Campeonato de la WWF)'] },
      { date: '10', location: 'Austin, TX', matches: ['Perry Saturn vs. Grandmaster Sexay', 'Edge & Christian vs. The Dudley Boyz (Bubba Ray & D-Von Dudley)', 'Dean Malenko vs. Scotty 2 Hotty', 'The Rock & Cactus Jack vs. The New Age Outlaws (Road Dogg & Billy Gunn) © (No por los títulos)', 'Luna Vachon & Gangrel vs. Jacqueline & Prince Albert', 'Rikishi vs. Chris Benoit', 'Al Snow & Steve Blackman vs. The Hardy Boyz (Matt Hardy & Jeff Hardy)', 'Chris Jericho © vs. Crash Holly (No DQ, Campeonato Intercontinental de la WWF)', 'Kane vs. Triple H & X-Pac (Handicap 2 vs. 1)', 'Kurt Angle vs. Val Venis © (Campeonato Europeo de la WWF)'] },
      { date: '17', location: 'Pittsburgh, PA', matches: ['Kane vs. Triple H © (Campeonato de la WWF)', 'Chyna vs. Kurt Angle © (Campeonato Europeo de la WWF)', 'Tazz vs. Gangrel', 'Cactus Jack vs. X-Pac (Falls Count Anywhere)', 'Perry Saturn & Dean Malenko vs. Too Cool (Scotty 2 Hotty & Grandmaster Sexay)', 'Eddie Guerrero vs. Rikishi', 'Edge & Christian vs. Big Boss Man & Prince Albert', 'Mark Henry vs. The Hollys (Hardcore Holly & Crash Holly) (Handicap 2 vs. 1)', 'The Rock vs. The New Age Outlaws (Road Dogg & Billy Gunn) © (Handicap 2 vs. 1, No por los títulos)'] },
      { date: '24', location: 'Nashville, TN', matches: ['Test © vs. Crash Holly (Campeonato Hardcore de la WWF)', 'Kurt Angle vs. Tazz', 'The Rock vs. X-Pac', 'Too Cool (Scotty 2 Hotty & Grandmaster Sexay) vs. Dean Malenko & Perry Saturn', 'The Dudley Boyz (Bubba Ray & D-Von Dudley) vs. The Acolytes (Bradshaw & Faarooq)', 'Rikishi & Cactus Jack vs. Big Show & Triple H', 'Chris Jericho vs. Chris Benoit (Campeonato Intercontinental de la WWF)'] },
    ],
    ppvs: [
      { date: '27', name: 'No Way Out', location: 'Hartford, CT', description: 'Triple H derrota a Cactus Jack en un Hell in a Cell para retener el título y retirar a Mick Foley. The Big Show derrota a The Rock.', matches: [{match: 'Hell in a Cell for WWF Championship: Triple H vs. Cactus Jack', rating: 5.0}, 'The Rock vs. The Big Show', 'WWF Intercontinental Championship: Kurt Angle vs. Chris Jericho', 'WWF Tag Team Championship: The Dudley Boyz vs. New Age Outlaws'], coverUrl: 'https://upload.wikimedia.org/wikipedia/en/e/ed/No_Way_Out_2000_logo.jpg' },
    ],
  },
  {
    month: 'Marzo',
    monthId: 'march',
    year: 2000,
    raw: [
        { date: '6', location: 'Springfield, MA', matches: ['Big Show vs. Kane', 'Mark Henry vs. D-Von Dudley', 'D-Generation X (Road Dogg & X-Pac) vs. Too Cool (Scotty 2 Hotty & Grandmaster Sexay)', 'Chris Jericho vs. Kurt Angle (Campeonato Intercontinental de la WWF)', 'Rikishi vs. Triple H', 'Steve Blackman vs. Matt Hardy', 'The Radicalz (Dean Malenko & Perry Saturn) vs. Edge & Christian', 'Crash Holly vs. Viscera (Campeonato Hardcore de la WWF [Regla 24/7])', 'The Rock vs. Chris Benoit (Jaula de acero)'] },
        { date: '13', location: 'East Rutherford, NJ', matches: ['The Hardy Boyz (Matt & Jeff Hardy) vs. Head Cheese (Al Snow & Steve Blackman)', 'The Dudley Boyz (Bubba Ray & D-Von Dudley) vs. Mark Henry (Handicap 2 vs. 1)', 'Kurt Angle vs. Chris Jericho vs. Tazz (Campeonato Europeo de la WWF - Triple amenaza)', 'D-Generation X (Triple H, X-Pac & Road Dogg) vs. Too Cool (Scotty 2 Hotty & Grandmaster Sexay) & Rikishi', 'Kane vs. Big Boss Man', 'Dean Malenko vs. Essa Rios (Campeonato Ligero de la WWF)', 'The Acolytes (Bradshaw & Faarooq) vs. Edge & Christian', 'Pete Gas vs. Crash Holly (Campeonato Hardcore de la WWF [Regla 24/7])', 'Crash Holly vs. Pete Gas (Campeonato Hardcore de la WWF [Regla 24/7])', 'The Radicalz (Chris Benoit & Perry Saturn) vs. Val Venis & Test', 'The Rock vs. Big Show (“Carrera de Rock en juego”)'] },
        { date: '20', location: 'Rosemont, IL', matches: ['The Hardy Boyz (Matt & Jeff Hardy) vs. D-Generation X (Road Dogg & X-Pac) (Torneo #1 Contender Campeonatos en Parejas de la WWF - Ronda 1)', 'The Godfather vs. Big Boss Man', 'Too Cool (Scotty 2 Hotty & Grandmaster Sexay) vs. The Radicalz (Dean Malenko & Perry Saturn) (Torneo #1 Contender Campeonatos en Parejas de la WWF - Ronda 1)', 'Kane vs. Rikishi', 'Chris Jericho vs. Chris Benoit', 'Head Cheese (Al Snow & Steve Blackman) vs. The Hollys (Hardcore & Crash Holly) (Torneo #1 Contender Campeonatos en Parejas de la WWF - Ronda 1)', 'Edge & Christian vs. The Acolytes (Bradshaw & Faarooq) (Torneo #1 Contender Campeonatos en Parejas de la WWF - Ronda 1)', 'Test vs. Val Venis', 'Edge & Christian vs. Too Cool (Scotty 2 Hotty & Grandmaster Sexay) vs. Head Cheese (Al Snow & Steve Blackman) vs. The Hardy Boyz (Matt & Jeff Hardy) (Torneo #1 Contender Campeonatos en Parejas de la WWF - Battle Royal final)', 'Triple H vs. The Rock vs. Big Show (Campeonato de la WWF - Triple amenaza)'] },
        { date: '27', location: 'Houston, TX', matches: ['The Radicalz (Eddie Guerrero & Chris Benoit) vs. Chris Jericho & Chyna', 'Crash Holly vs. Hardcore Holly (Campeonato Hardcore de la WWF [Regla 24/7])', 'Rikishi vs. Road Dogg', 'The Radicalz (Dean Malenko & Perry Saturn) vs. The Hardy Boyz (Matt & Jeff Hardy)', 'Kane vs. Kurt Angle', 'Test vs. Al Snow', 'D\'Lo Brown & The Godfather vs. Big Boss Man & Bull Buchanan', 'X-Pac vs. D-Von Dudley', 'Vince McMahon & The Rock vs. Shane McMahon & Big Show (Árbitros especiales: Triple H & Mick Foley)'] },
    ],
    smackdown: [
        { date: '2', location: 'San Jose, CA', matches: ['The Radicalz (Chris Benoit, Dean Malenko & Perry Saturn) vs. Chris Jericho & Too Cool (Scotty 2 Hotty & Grandmaster Sexay)', 'Jeff Hardy vs. Essa Rios (Campeonato Ligero de la WWF)', 'Crash Holly vs. Tazz (Campeonato Hardcore de la WWF [Regla 24/7])', 'D-Generation X (X-Pac & Road Dogg) vs. Edge & Christian', 'Test vs. Viscera', 'Kurt Angle vs. Sgt. Slaughter', 'The Dudley Boyz (Bubba Ray & D-Von Dudley) vs. Kane (Handicap 2 vs. 1)', 'The Rock & Rikishi vs. Triple H & Big Show'] },
        { date: '9', location: 'East Rutherford, NJ', matches: ['The Rock vs. The Radicalz (Chris Benoit & Perry Saturn) (Handicap 2 vs. 1)', 'Essa Rios vs. Christian (Campeonato Ligero de la WWF)', 'Tazz vs. Kurt Angle (Campeonato Intercontinental de la WWF)', 'D-Generation X (X-Pac & Road Dogg) vs. Kane (Handicap 2 vs. 1)', 'Steve Blackman vs. Jeff Hardy', 'The Dudley Boyz (Bubba Ray & D-Von Dudley) vs. The Rock (Handicap 2 vs. 1 - Lucha de mesas)', 'Jacqueline vs. Ivory (Campeonato Femenino de la WWF)', 'Crash Holly vs. Prince Albert (Campeonato Hardcore de la WWF [Regla 24/7])', 'Triple H & Big Show vs. Rikishi (Handicap 2 vs. 1)'] },
        { date: '16', location: 'Cleveland, OH', matches: ['The Dudley Boyz (Bubba Ray & D-Von Dudley) vs. Edge & Christian (Campeonatos en Parejas de la WWF)', 'The Godfather vs. Triple H', 'The Acolytes (Bradshaw & Faarooq) vs. Head Cheese (Al Snow & Steve Blackman)', 'Rikishi vs. Big Show', 'Chris Jericho & Tazz vs. Kurt Angle & Bob Backlund', 'Crash Holly vs. The Headbangers (Mosh & Thrasher) (Campeonato Hardcore de la WWF [Regla 24/7] - Handicap 2 vs. 1)', 'Dean Malenko vs. Brian Christopher (Campeonato Ligero de la WWF)', 'The Hardy Boyz (Matt & Jeff Hardy) vs. The Radicalz (Chris Benoit & Perry Saturn)', 'The Rock vs. X-Pac'] },
        { date: '23', location: 'Chicago, IL', matches: ['Kurt Angle vs. Chris Benoit', 'The Godfather vs. Bull Buchanan', 'Head Cheese (Al Snow & Steve Blackman) vs. The Hollys (Hardcore & Crash Holly)', 'The Rock vs. Bubba Ray Dudley', 'Jacqueline vs. Lita (Campeonato Femenino de la WWF)', 'Too Cool (Scotty 2 Hotty & Grandmaster Sexay) & Rikishi vs. The Radicalz (Eddie Guerrero, Dean Malenko & Perry Saturn)'] },
        { date: '30', location: 'San Antonio, TX', matches: ['Kane & Rikishi vs. The Dudley Boyz (Bubba Ray & D-Von Dudley)', 'Crash Holly vs. Tazz (Campeonato Hardcore de la WWF [Regla 24/7])', 'D-Generation X (X-Pac & Road Dogg) vs. Edge & Christian', 'The Rock vs. Kurt Angle', 'Chris Jericho vs. Eddie Guerrero', 'Dean Malenko vs. Scotty 2 Hotty (Campeonato Ligero de la WWF)', 'The Hardy Boyz (Matt & Jeff Hardy) vs. T & A (Test & Albert)', 'Stephanie McMahon-Helmsley vs. Jacqueline (Campeonato Femenino de la WWF)'] },
    ],
    ppvs: [],
  },
  {
    month: 'Abril',
    monthId: 'april',
    year: 2000,
    raw: [
        { date: '3', location: 'Los Ángeles, CA', matches: ['Eddie Guerrero vs. Chris Jericho (Campeonato Europeo de la WWF)', 'Road Dogg & X-Pac vs. T&A (Test & Albert)', 'Chris Benoit © vs. Tazz (Campeonato Intercontinental de la WWF)', 'The Big Show vs. Rikishi', 'Crash Holly vs. Hardcore Holly (Campeonato Hardcore de la WWF)', 'Kurt Angle vs. Val Venis', 'Kane vs. Bull Buchanan', 'The Rock vs. Shane McMahon'] },
        { date: '10', location: 'East Rutherford, NJ', matches: ['Edge & Christian © vs. Road Dogg & X-Pac (Campeonatos en Parejas de la WWF)', 'Kurt Angle vs. The Godfather', 'Chris Benoit, Perry Saturn & Dean Malenko vs. Scott Taylor, Rikishi & Tazz', 'Triple H © vs. Taka Michinoku (Campeonato de la WWF)', 'The Hardy Boyz (Matt & Jeff Hardy) vs. T&A (Test & Albert)', 'Val Venis vs. The Big Show', 'Eddie Guerrero © vs. Chris Jericho (Campeonato Europeo de la WWF)', 'The Rock vs. Big Boss Man & Bull Buchanan (Jaula de acero)'] },
        { date: '17', location: 'State College, PA', matches: ['Triple H © vs. Chris Jericho (Campeonato de la WWF)', 'The Hardy Boyz (Matt & Jeff Hardy) vs. Essa Rios & Eddie Guerrero', 'Crash Holly © vs. Tazz & Perry Saturn (Campeonato Hardcore de la WWF - Triple amenaza)', 'Al Snow & Steve Blackman vs. The Dudley Boyz (Bubba Ray & D-Von Dudley)', 'Scotty 2 Hotty vs. Dean Malenko (Campeonato Ligero de la WWF)', 'The Big Show vs. Chris Benoit © (Campeonato Intercontinental de la WWF)', 'Edge & Christian © vs. Big Boss Man & Bull Buchanan (Campeonatos en Parejas de la WWF)', 'Road Dogg, X-Pac & Triple H vs. Chris Jericho & The Acolytes (Bradshaw & Faarooq)'] },
        { date: '24', location: 'Raleigh, NC', matches: ['Rikishi vs. Kurt Angle', 'Chris Benoit © vs. Road Dogg (Campeonato Intercontinental de la WWF)', 'The Hollys (Hardcore & Crash Holly) vs. The Hardy Boyz (Matt & Jeff Hardy)', 'Matt Hardy vs. Crash Holly (Campeonato Hardcore de la WWF)', 'The Big Show vs. Big Boss Man & Bull Buchanan', 'D\'Lo Brown & Steve Blackman vs. Al Snow & The Godfather', 'Val Venis vs. Eddie Guerrero © (No por el título; Campeonato Europeo de la WWF)', 'Edge & Christian © vs. The Dudley Boyz (Bubba Ray & D-Von Dudley) (Campeonatos en Parejas de la WWF)', 'Triple H & Chris Benoit vs. The Rock & Chris Jericho'] },
    ],
    smackdown: [
        { date: '6', location: 'San José, CA', matches: ['Chris Benoit © vs. Rikishi (Campeonato Intercontinental de la WWF)', 'The Dudley Boyz (Bubba Ray & D-Von Dudley) vs. T&A (Test & Albert)', 'Tazz vs. Perry Saturn', 'Big Boss Man & Bull Buchanan vs. Al Snow & Steve Blackman', 'Dean Malenko © vs. Taka Michinoku (Campeonato Ligero de la WWF)', 'The Big Show vs. The Godfather', 'Edge & Christian © vs. Kurt Angle & Hardcore Holly (Campeonatos en Parejas de la WWF)', 'Road Dogg & X-Pac vs. The Rock (Handicap 2 vs. 1; Árbitro especial: Triple H)'] },
        { date: '13', location: 'Phoenix, AZ', matches: ['Rikishi vs. Eddie Guerrero © (Campeonato Europeo de la WWF)', 'The Hardy Boyz (Matt & Jeff Hardy) vs. Chris Benoit & Dean Malenko', 'Perry Saturn vs. Crash Holly © (Campeonato Hardcore de la WWF)', 'Tazz vs. Perry Saturn (Campeonato Hardcore de la WWF)', 'Crash Holly vs. Tazz (Campeonato Hardcore de la WWF)', 'Edge & Christian © vs. Kurt Angle & The Big Show (Campeonatos en Parejas de la WWF)', 'Bubba Ray Dudley vs. Albert', 'The Kat & Mae Young vs. The Fabulous Moolah & Terri Runnells', 'Road Dogg & X-Pac vs. Chris Jericho (Handicap 2 vs. 1)', 'The Rock & The Acolytes (Bradshaw & Faarooq) vs. Triple H, Big Boss Man & Bull Buchanan'] },
        { date: '20', location: 'Filadelfia, PA', matches: ['Road Dogg vs. Edge', 'The Dudley Boyz (Bubba Ray & D-Von Dudley) vs. Essa Rios & Eddie Guerrero', 'Rikishi vs. The Big Show', 'Triple H © vs. Tazz (Campeonato de la WWF)', 'T&A (Test & Albert) vs. The Godfather & D\'Lo Brown', 'X-Pac vs. Christian', 'Chris Benoit © vs. Kurt Angle (Campeonato Intercontinental de la WWF)', 'Chris Jericho vs. The Rock (Lucha Lumberjack)'] },
        { date: '27', location: 'Charlotte, NC', matches: ['Essa Rios & Val Venis vs. Eddie Guerrero & Chyna', 'Dean Malenko vs. Scotty 2 Hotty © (Campeonato Ligero de la WWF)', 'T&A (Test & Albert) vs. The Hollys (Hardcore & Crash Holly)', 'Chris Jericho & Tazz vs. Perry Saturn & Chris Benoit', 'Christian vs. Road Dogg', 'Rikishi & The Big Show vs. Big Boss Man, Bull Buchanan & Kurt Angle (Handicap 3 vs. 2)', 'Crash Holly vs. Matt Hardy (Campeonato Hardcore de la WWF)', 'The Godfather vs. Steve Blackman'] },
    ],
    ppvs: [
      { date: '2', name: 'WrestleMania 2000', location: 'Anaheim, CA', description: 'Una lucha fatal de 4 esquinas por el título. Vince McMahon traiciona a The Rock, permitiendo que Triple H retenga.', matches: ['WWF Championship: Triple H vs. The Rock vs. The Big Show vs. Mick Foley', {match: 'Triangle Ladder Match: Edge & Christian vs. The Hardy Boyz vs. The Dudley Boyz', rating: 4.5}, 'Two-Fall Intercontinental & European Championship Match: Kurt Angle vs. Chris Benoit vs. Chris Jericho'], coverUrl: 'https://upload.wikimedia.org/wikipedia/en/a/ab/WM2000Poster.jpeg' },
      { date: '30', name: 'Backlash', location: 'Washington, D.C.', description: '¡The Rock finalmente derrota a Triple H para ganar el Campeonato de la WWF, gracias a la ayuda de Stone Cold Steve Austin!', matches: ['Edge y Christian © vs. D-Generation X (Road Dogg y X-Pac) (con Tori) (Campeonatos en Parejas de la WWF)', 'Dean Malenko © vs. Scotty 2 Hotty (Campeonato Ligero de la WWF)', 'Bull Buchanan y Big Boss Man vs. The APA (Bradshaw y Faarooq)', 'Crash Holly © vs. Hardcore Holly, Jeff Hardy, Matt Hardy, Perry Saturn y Tazz (Lucha hardcore de seis hombres por el Campeonato Hardcore de la WWF)', 'Big Show vs. Kurt Angle', 'T&A (Albert y Test) (con Trish Stratus) vs. The Dudley Boyz (Bubba Ray Dudley y D-Von Dudley)', 'Eddie Guerrero © (con Chyna) vs. Essa Rios (con Lita) (Campeonato Europeo de la WWF)', 'Chris Benoit © vs. Chris Jericho (Campeonato Intercontinental de la WWF)', { match: 'Triple H © (con Mr. McMahon y Stephanie McMahon-Helmsley) vs. The Rock (Campeonato de la WWF; Árbitro especial: Shane McMahon)', rating: 4.5 }], coverUrl: 'https://upload.wikimedia.org/wikipedia/en/c/c6/Backlash_2000_poster.jpg' },
    ],
  },
  {
    month: 'Mayo',
    monthId: 'may',
    year: 2000,
    raw: [
      { date: '1', location: 'Baltimore, MD', matches: ['T & A (Albert & Test) vs. The Dudley Boyz (Bubba Ray & D-Von Dudley)', 'Too Cool (Scotty 2 Hotty & Grandmaster Sexay) vs. The Hardy Boyz (Matt & Jeff Hardy)', 'The Kat & Jacqueline vs. Terri & Ivory', 'Chris Jericho vs. X-Pac', 'Rikishi & Showkishi (Big Show) vs. Edge & Christian (Campeonatos en Parejas de la WWF)', 'Eddie Guerrero vs. Essa Rios (Campeonato Europeo de la WWF)', 'Chris Benoit vs. Tazz (Campeonato Intercontinental de la WWF)', 'Crash Holly vs. Steve Blackman (Campeonato Hardcore de la WWF [Regla 24/7])', 'The Rock vs. Shane McMahon (Campeonato de la WWF - Jaula de acero; Árbitros especiales: Pat Patterson & Gerald Brisco)'] },
      { date: '8', location: 'Kansas City, MO', matches: ['Edge & Christian vs. The APA (Bradshaw & Faarooq) (Campeonatos en Parejas de la WWF)', 'Chris Jericho vs. Kurt Angle (Campeonato Intercontinental de la WWF)', 'Eddie Guerrero vs. The Godfather', 'The Dudley Boyz (Bubba Ray & D-Von Dudley) vs. T & A (Test & Albert) & Gerald Brisco (Handicap 3 vs. 2 - Lucha de mesas)', 'Chris Jericho vs. Big Show (Campeonato Intercontinental de la WWF)', 'Too Cool (Scotty 2 Hotty & Grandmaster Sexay) vs. Big Boss Man & Bull Buchanan', 'The Hardy Boyz (Matt & Jeff Hardy) vs. The Radicalz (Dean Malenko & Perry Saturn)', 'Rikishi vs. D-Generation X (Road Dogg & X-Pac) & Pat Patterson (Handicap 3 vs. 1)', 'Chris Benoit vs. Chris Jericho (Campeonato Intercontinental de la WWF; Árbitro especial: Triple H)'] },
      { date: '15', location: 'Washington, D.C.', matches: ['The Dudley Boyz (Bubba Ray & D-Von Dudley) vs. Al Snow & Steve Blackman', 'Rikishi vs. Kurt Angle', 'Crash Holly vs. The Godfather (Campeonato Hardcore de la WWF [Regla 24/7])', 'Hardcore Holly vs. Chris Jericho (Lucha hardcore)', 'Big Show vs. T & A (Test & Albert) (Handicap 2 vs. 1)', 'The Radicalz (Dean Malenko & Perry Saturn) vs. Eddie Guerrero & Chyna', 'Edge & Christian vs. The APA (Bradshaw & Faarooq) vs. The Hardy Boyz (Matt & Jeff Hardy) (Campeonatos en Parejas de la WWF - Triple amenaza)', 'Chris Benoit vs. The Rock (Lucha de sumisión)'] },
      { date: '22', location: 'Albany, NY', matches: ['T & A (Albert & Test) vs. The Hardy Boyz (Matt & Jeff Hardy)', 'Eddie Guerrero vs. D’Lo Brown (Campeonato Europeo de la WWF)', 'Kurt Angle, Edge & Christian vs. Rikishi & Too Cool (Scotty 2 Hotty & Grandmaster Sexay)', 'Chris Benoit vs. Val Venis (Campeonato Intercontinental de la WWF)', 'The Dudley Boyz (Bubba Ray & D-Von Dudley) vs. Big Boss Man & Bull Buchanan', 'Bradshaw vs. Crash Holly (Lucha hardcore)', 'The Radicalz (Dean Malenko & Perry Saturn) vs. Essa Rios & The Godfather'] },
      { date: '29', location: 'Vancouver, BC', matches: ['D\'Lo Brown, Perry Saturn & Terri Runnells vs. Dean Malenko, The Godfather & The Kat', 'Eddie Guerrero vs. Kurt Angle (Campeonato Europeo de la WWF)', 'Too Cool (Scotty 2 Hotty & Grandmaster Sexay) vs. Edge & Christian (Campeonatos en Parejas de la WWF)', 'Rikishi vs. Shane McMahon (Calificatoria King of the Ring 2000)', 'T & A (Test & Albert) & Val Venis vs. The Hardy Boyz (Matt & Jeff Hardy) & Chris Jericho', 'Hardcore Holly vs. Chris Benoit (Campeonato Intercontinental de la WWF)', 'Bull Buchanan vs. Steve Blackman (Calificatoria King of the Ring 2000)', 'The Undertaker vs. The Rock (Lucha lumberjack)'] },
    ],
    smackdown: [
      { date: '4', location: 'Phoenix, AZ', matches: ['Chris Jericho vs. Chris Benoit (Campeonato Intercontinental de la WWF)', 'Eddie Guerrero & Chyna vs. Essa Rios & Lita', 'Kurt Angle vs. Hardcore Holly', 'Rikishi vs. Edge & Christian (Handicap 2 vs. 1)', 'The Hardy Boyz (Matt & Jeff Hardy) vs. T & A (Test & Albert)', 'Big Show vs. Bull Buchanan', 'Crash Holly vs. Dean Malenko (Campeonato Hardcore de la WWF)', 'The Rock & Earl Hebner vs. D-Generation X (Triple H, X-Pac & Road Dogg) (Handicap 3 vs. 2)'] },
      { date: '11', location: 'New Haven, CT', matches: ['T & A (Test & Albert) vs. The Dudley Boyz (Bubba Ray & D-Von Dudley)', 'Chris Benoit vs. The Godfather (Campeonato Intercontinental de la WWF)', 'Dean Malenko vs. Chyna (Campeonato Ligero de la WWF)', 'Kurt Angle, Edge & Christian vs. Chris Jericho & The Hardy Boyz (Matt & Jeff Hardy)', 'The British Bulldog vs. Crash Holly (Campeonato Hardcore de la WWF)', 'The Dudley Boyz (Bubba Ray & D-Von Dudley) vs. Big Show (Handicap 2 vs. 1 - Lucha de mesas)', 'Eddie Guerrero vs. Perry Saturn (Campeonato Europeo de la WWF)', 'D-Generation X (Triple H, X-Pac & Road Dogg) vs. Too Cool (Scotty 2 Hotty & Grandmaster Sexay) & Rikishi (Lucha de eliminación)'] },
      { date: '18', location: 'Detroit, MI', matches: ['Kurt Angle vs. Scotty 2 Hotty', 'Dean Malenko vs. Perry Saturn (#1 Contender Campeonato Europeo de la WWF)', 'Grandmaster Sexay vs. Christian', 'Chris Jericho & Val Venis vs. Chris Benoit & Hardcore Holly', 'Rikishi vs. Edge', 'Shane McMahon, T & A (Test & Albert), Big Boss Man, Bull Buchanan & D-Generation X (X-Pac & Road Dogg) vs. Big Show (Gauntlet 7 vs. 1)', 'Gerald Brisco vs. Crash Holly (Campeonato Hardcore de la WWF)', 'Gerald Brisco vs. Crash Holly (Campeonato Hardcore de la WWF)', 'The Dudley Boyz (Bubba Ray & D-Von Dudley) vs. The Rock (Handicap 2 vs. 1 - Lucha lumberjack)'] },
      { date: '25', location: 'Oklahoma City, OK', matches: ['Eddie Guerrero & Chyna vs. Edge & Christian (Campeonatos en Parejas de la WWF)', 'Faarooq vs. Crash Holly (Lucha hardcore)', 'Hardcore Holly vs. Chris Jericho vs. Val Venis (#1 Contender Campeonato Intercontinental de la WWF - Triple amenaza)', 'Matt Hardy vs. Essa Rios', 'The Dudley Boyz (Bubba Ray & D-Von Dudley) & Too Cool (Scotty 2 Hotty & Grandmaster Sexay) vs. T & A (Test & Albert) & D-Generation X (X-Pac & Road Dogg)', 'Kurt Angle vs. Chris Benoit (Campeonato Intercontinental de la WWF)', 'Bull Buchanan vs. Al Snow', 'The Undertaker vs. Shane McMahon'] },
    ],
    ppvs: [
      { date: '21', name: 'Judgment Day', location: 'Louisville, KY', matches: ['Too Cool (Scotty 2 Hotty & Grandmaster Sexay) & Rikishi vs. Edge, Christian & Kurt Angle', 'Eddie Guerrero vs. Dean Malenko vs. Perry Saturn (Campeonato Europeo de la WWF - Lucha triangular)', 'Shane McMahon vs. Big Show (Lucha Falls Count Anywhere)', 'Chris Benoit vs. Chris Jericho (Campeonato Intercontinental de la WWF - Lucha de sumisión)', 'Road Dogg & X-Pac vs. The Dudley Boyz (Bubba Ray & D-Von Dudley) (Lucha de mesas doble)', {match:'Triple H vs. The Rock (Campeonato de la WWF - Iron Man Match de 60 minutos)', rating: 4.8}], coverUrl: 'https://upload.wikimedia.org/wikipedia/en/3/3d/2000JudgmentDay.jpg' },
    ],
  },
  {
    month: 'Junio',
    monthId: 'june',
    year: 2000,
    raw: [
      { date: '5', location: 'Rochester, NY', matches: ['T&A (Albert & Test) & Val Venis (w/ Trish Stratus) vs. Rikishi & Too Cool (Scotty 2 Hotty & Grandmaster Sexay)', 'Chris Benoit vs. The Godfather (Calificatoria King of the Ring 2000)', 'Eddie Guerrero (w/ Chyna) vs. Crash Holly © (Campeonato Hardcore de la WWF)', 'Perry Saturn vs. Al Snow (Calificatoria King of the Ring 2000)', 'The Rock vs. Shane McMahon (w/ Vince McMahon, Stephanie McMahon-Helmsley & Triple H)', 'Chris Jericho © (w/ Chris Benoit) vs. Rikishi (w/ Too Cool) (Campeonato Intercontinental de la WWF)', 'Edge & Christian © (w/ Rhyno) vs. Too Cool (Grandmaster Sexay & Scotty 2 Hotty) & Rikishi (Campeonatos en Parejas de la WWF)', 'Triple H © (w/ Stephanie McMahon-Helmsley) vs. The Rock (w/ Vince McMahon) (Campeonato de la WWF)'] },
      { date: '12', location: 'St. Louis, MO', matches: ['X-Pac (w/ Road Dogg & Tori) vs. Dean Malenko (Calificatoria King of the Ring 2000)', 'Stephanie McMahon-Helmsley © (w/ Triple H) vs. Lita (w/ The Hardy Boyz) (Campeonato Femenino de la WWF)', 'The Rock vs. Kurt Angle (w/ Stephanie McMahon-Helmsley)', 'Chris Benoit (w/ Perry Saturn & Dean Malenko) vs. Road Dogg (w/ X-Pac)', 'Chris Jericho © vs. Val Venis (w/ Trish Stratus) (Campeonato Intercontinental de la WWF)', 'Kane vs. Bull Buchanan (w/ Big Boss Man)', 'Edge & Christian © (w/ Rhyno) vs. The Hardy Boyz (Matt & Jeff Hardy) & The Dudley Boyz (Bubba Ray & D-Von Dudley) (Campeonatos en Parejas de la WWF)', 'The Undertaker vs. Shane McMahon (w/ Vince McMahon, Triple H & Stephanie McMahon-Helmsley) (No Holds Barred)'] },
      { date: '19', location: 'Nashville, TN', matches: ['Crash Holly © vs. The Godfather (Campeonato Hardcore de la WWF)', 'The Rock vs. T&A (Albert & Test) (w/ Trish Stratus) (Handicap 2 vs. 1)', 'Chris Benoit vs. X-Pac (w/ Road Dogg) (Primera Ronda King of the Ring 2000)', 'Eddie Guerrero (w/ Chyna) vs. Perry Saturn (w/ Terri Runnels) (Campeonato Europeo de la WWF)', 'The Dudley Boyz (Bubba Ray & D-Von Dudley) vs. Too Cool (Grandmaster Sexay & Scotty 2 Hotty) (w/ Rikishi) (Lucha de mesas)', 'Kane vs. Val Venis (w/ Trish Stratus)', 'Chris Jericho © (w/ Chris Benoit) vs. Rikishi (w/ Too Cool) (Campeonato Intercontinental de la WWF)', 'Kurt Angle vs. Road Dogg (w/ X-Pac) (Primera Ronda King of the Ring 2000)', 'Kane vs. The Rock (No Holds Barred)'] },
      { date: '26', location: 'Worcester, MA', matches: ['The APA (Bradshaw & Faarooq) vs. The Dudley Boyz (Bubba Ray & D-Von Dudley)', 'Crash Holly © vs. Hardcore Holly (Campeonato Hardcore de la WWF)', 'Chris Benoit vs. Rikishi © (w/ Too Cool) (Campeonato Intercontinental de la WWF)', 'Eddie Guerrero (w/ Chyna) vs. Dean Malenko (w/ Terri Runnels) (Campeonato Europeo de la WWF)', 'The Hardy Boyz (Matt & Jeff Hardy) vs. T&A (Test & Albert) (w/ Trish Stratus)', 'The Rock vs. Triple H © (w/ Stephanie McMahon-Helmsley) & Kurt Angle (Triple amenaza por candidatura #1 al Campeonato de la WWF)'] },
    ],
    smackdown: [
      { date: '1', location: 'Uniondale, NY', matches: ['The Hardy Boyz (Matt & Jeff Hardy) vs. Too Cool (Scotty 2 Hotty & Grandmaster Sexay) © (Campeonatos en Parejas de la WWF)', 'Chris Jericho vs. Crash Holly © (w/ Molly Holly) (Campeonato Hardcore de la WWF)', 'T&A (Test & Albert) (w/ Trish Stratus) vs. The Acolytes (Bradshaw & Faarooq)', 'Kane vs. Jeff Hardy', 'Eddie Guerrero © (w/ Chyna) vs. Perry Saturn (w/ Terri) (Campeonato Europeo de la WWF)', 'The Rock vs. Bull Buchanan (w/ Big Boss Man)', 'Triple H © (w/ Stephanie McMahon-Helmsley) vs. Kane (Campeonato de la WWF)'] },
      { date: '8', location: 'Buffalo, NY', matches: ['Chris Jericho vs. Test (w/ Trish Stratus) (Calificatoria King of the Ring 2000)', 'Too Cool (Scotty 2 Hotty & Grandmaster Sexay) © (w/ Rikishi) vs. The Godfather & Dean Malenko (Campeonatos en Parejas de la WWF)', 'The Rock vs. Christian (w/ Edge)', 'Rikishi © (w/ Too Cool) vs. Chris Benoit (Campeonato Intercontinental de la WWF)', 'The Undertaker vs. Albert (w/ Trish Stratus & Test)', 'Kane vs. Big Boss Man (w/ Bull Buchanan)', 'Edge & Christian vs. The Hardy Boyz (Matt & Jeff Hardy) (w/ Lita)'] },
      { date: '15', location: 'Chicago, IL', matches: ['Edge (w/ Christian) vs. Grandmaster Sexay (w/ Scotty 2 Hotty) (Calificatoria King of the Ring 2000)', 'T&A (Albert & Test) (w/ Trish Stratus) vs. The Dudley Boyz (Bubba Ray & D-Von Dudley)', 'Eddie Guerrero © (w/ Chyna) vs. Dean Malenko (w/ Terri Runnels) (Campeonato Europeo de la WWF)', 'Chris Benoit vs. Perry Saturn (w/ Terri Runnels)', 'Too Cool (Grandmaster Sexay & Scotty 2 Hotty) © (w/ Rikishi) vs. The Acolytes (Bradshaw & Faarooq) (Campeonatos en Parejas de la WWF)', 'The McMahon-Helmsley Regime (Triple H, Vince McMahon & Shane McMahon) (w/ Stephanie McMahon-Helmsley) vs. The Rock, The Undertaker & Kane (Lucha en equipo de 6 hombres)'] },
      { date: '22', location: 'Memphis, TN', matches: ['T&A (Test & Albert) & Trish Stratus vs. The Hardy Boyz (Matt & Jeff Hardy) & Lita', 'Rikishi © (w/ Too Cool) vs. Kurt Angle (w/ Stephanie McMahon-Helmsley) (Campeonato Intercontinental de la WWF)', 'Big Boss Man (w/ Bull Buchanan) vs. Crash Holly © (w/ Molly Holly) (Campeonato Hardcore de la WWF)', 'Shane McMahon, Triple H © (w/ Stephanie McMahon-Helmsley) & Vince McMahon vs. The Rock, The Undertaker & Kane (Lucha en equipo de 6 hombres)', 'The APA (Bradshaw & Faarooq) vs. The Dudley Boyz (Bubba Ray & D-Von Dudley) & Too Cool (Grandmaster Sexay & Scotty 2 Hotty) (w/ Rikishi) (Handicap 2 vs. 4)'] },
      { date: '29', location: 'Birmingham, AL', matches: ['Chris Benoit & Val Venis vs. Eddie Guerrero & Rikishi (w/ Chyna)', 'Kurt Angle vs. Hardcore Holly', 'Bull Buchanan (w/ Big Boss Man) vs. The Godfather (w/ the hos)', 'Perry Saturn (w/ Terri) vs. Dean Malenko (Campeonato Europeo de la WWF)', 'Edge & Christian © (w/ Rhyno) vs. Too Cool (Grandmaster Sexay & Scotty 2 Hotty) (w/ Rikishi) (Campeonatos en Parejas de la WWF)', 'Kane vs. Christian (w/ Edge)'] },
    ],
    ppvs: [
      { date: '25', name: 'King of the Ring', location: 'Boston, MA', description: 'Kurt Angle gana el torneo. The Rock recupera el Campeonato de la WWF de Triple H en una lucha de equipos de seis hombres.', matches: ['Rikishi vs. Chris Benoit (Cuartos de final del Torneo King of the Ring)', 'Val Venis (w/ Trish Stratus) vs. Eddie Guerrero (w/ Chyna) (Cuartos de final del Torneo King of the Ring)', 'Crash Holly vs. Bull Buchanan (Cuartos de final del Torneo King of the Ring)', 'Kurt Angle vs. Chris Jericho (Cuartos de final del Torneo King of the Ring)', 'Too Cool (Grand Master Sexay & Scotty 2 Hotty) © vs. Edge & Christian vs. The Hardy Boyz (Jeff Hardy & Matt Hardy) (w/ Lita) vs. T&A (Albert & Test) (w/ Trish Stratus) (Campeonatos en Parejas de la WWF - Lucha de eliminación fatal 4-way)', 'Rikishi vs. Val Venis (w/ Trish Stratus) (Semifinales del Torneo King of the Ring)', 'Kurt Angle vs. Crash Holly (Semifinales del Torneo King of the Ring)', 'Pat Patterson © vs. Gerald Brisco (Campeonato Hardcore de la WWF - Lucha Evening Gown Hardcore)', 'D-Generation X (Tori, Road Dogg & X-Pac) vs. The Dudley Boyz (Bubba Ray Dudley & D-Von Dudley) (Handicap Tables Dumpster Match)', 'Kurt Angle vs. Rikishi (Final del Torneo King of the Ring)', 'The Rock & The Brothers of Destruction (Kane & The Undertaker) vs. The McMahon-Helmsley Faction (Mr. McMahon, Shane McMahon & Triple H © w/ Stephanie McMahon-Helmsley) (Lucha en equipo de 6 hombres por el Campeonato de la WWF)'] },
    ],
  },
  {
    month: 'Julio',
    monthId: 'july',
    year: 2000,
    raw: [
      { date: '3', location: 'Orlando, FL', matches: ['Eddie Guerrero © vs. Chris Benoit (Campeonato Europeo de la WWF)', 'Rikishi © vs. Triple H (Campeonato Intercontinental de la WWF)', 'Val Venis vs. Jeff Hardy', 'Chris Jericho & The APA (Bradshaw & Faarooq) vs. D-Generation X (Road Dogg & X-Pac) (Handicap 3 vs. 2)', 'The Brothers of Destruction (The Undertaker & Kane) vs. Edge & Christian © (Campeonatos en Parejas de la WWF)', 'Dean Malenko © vs. Crash Holly (Campeonato Ligero de la WWF)', 'The Dudley Boyz (Bubba Ray & D-Von Dudley) vs. Kurt Angle & The Brooklyn Brawler', 'Test vs. The Godfather', 'The Rock © vs. Shane McMahon (Campeonato de la WWF)']},
      { date: '10', location: 'New York, NY', matches: ['T & A (Test & Albert) vs. Too Cool (Scotty 2 Hotty & Grandmaster Sexay) vs. The Hardy Boyz (Matt & Jeff Hardy) (Triple amenaza de eliminación)', 'Chris Jericho vs. Road Dogg', 'Val Venis © vs. Kane vs. Rikishi (Campeonato Intercontinental de la WWF - Triple amenaza)', 'Edge vs. Bradshaw', 'Lita vs. Trish Stratus (Street Fight)', 'Triple H vs. X-Pac', 'The Rock vs. Chris Benoit (#1 Contender Campeonato de la WWF)'] },
      { date: '17', location: 'Philadelphia, PA', matches: ['The Dudley Boyz (Bubba Ray & D-Von Dudley) vs. The Hardy Boyz (Matt & Jeff Hardy)', 'Steve Blackman © vs. The Godfather (Campeonato Hardcore de la WWF)', 'D-Generation X (Road Dogg & X-Pac) vs. Too Cool (Scotty 2 Hotty & Grandmaster Sexay)', 'Chris Benoit, Edge & Christian vs. The Rock & The APA (Bradshaw & Faarooq)', 'Dean Malenko © vs. Chyna (Campeonato Ligero de la WWF)', 'Rikishi vs. Test', 'The Brothers of Destruction (The Undertaker & Kane) vs. Triple H & Kurt Angle'] },
      { date: '24', location: 'San Antonio, TX', matches: ['Steve Blackman © vs. Road Dogg (Campeonato Hardcore de la WWF)', 'Big Show & Lita vs. Shane McMahon & Stephanie McMahon-Helmsley', 'Bull Buchanan vs. The Godfather (High Stakes Match)', 'Kurt Angle vs. The Undertaker', 'Tazz vs. Scotty 2 Hotty', 'Edge & Christian © vs. The Dudley Boyz (Bubba Ray & D-Von Dudley) vs. The Hardy Boyz (Matt & Jeff Hardy) (Campeonatos en Parejas de la WWF - Triple amenaza)', 'Trish Stratus vs. Lita (Strap Match)', 'The Rock & Kane vs. Kurt Angle & Chris Benoit'] },
      { date: '31', location: 'Atlanta, GA', matches: ['D-Generation X (Road Dogg & X-Pac) vs. Al Snow & Steve Blackman (Hardcore Match)', 'The Hardy Boyz (Matt & Jeff Hardy) vs. Edge & Christian © (Campeonatos en Parejas de la WWF)', 'Kurt Angle & Chris Benoit vs. The Dudley Boyz (Bubba Ray & D-Von Dudley)', 'The APA (Bradshaw & Faarooq) vs. Right to Censor (Bull Buchanan & The Godfather)', 'Rikishi vs. Tazz', 'Eddie Guerrero & Chyna vs. Val Venis & Perry Saturn', 'Big Show vs. Kane', 'The Rock & Lita vs. Triple H & Trish Stratus'] },
    ],
    smackdown: [
      { date: '6', location: 'Miami, FL', matches: ['Kurt Angle vs. Chris Jericho', 'The Dudley Boyz (Bubba Ray & D-Von Dudley) vs. Lo Down (D\'Lo Brown & Chaz)', 'Jacqueline & Ivory vs. Dean Malenko (Handicap 2 vs. 1)', 'Val Venis vs. Rikishi (Campeonato Intercontinental de la WWF)', 'Steve Blackman vs. Big Boss Man (Campeonato Hardcore de la WWF)', 'The Brothers of Destruction (The Undertaker & Kane) vs. T & A (Test & Albert)', 'Kaientai (Taka Michinoku & Funaki) & The Brooklyn Brawler vs. Triple H (Handicap 3 vs. 1 de eliminación)', 'The Rock, Eddie Guerrero & Chyna vs. Edge, Christian & Chris Benoit'] },
      { date: '13', location: 'Louisville, KY', matches: ['Too Cool (Scotty 2 Hotty & Grandmaster Sexay) & Rikishi vs. T & A (Test & Albert) & Val Venis', 'D-Generation X (X-Pac & Road Dogg) vs. The Hardy Boyz (Matt & Jeff Hardy)', 'Dean Malenko vs. Al Snow', 'Eddie Guerrero & Chyna vs. Chris Benoit (Handicap 2 vs. 1)', 'Faarooq vs. Christian', 'Kane vs. Kurt Angle', 'Steve Blackman vs. Crash Holly (Campeonato Hardcore de la WWF)', 'Triple H vs. The Undertaker (No DQ)'] },
      { date: '20', location: 'Long Island, NY', matches: ['Eddie Guerrero vs. Dean Malenko vs. Perry Saturn (Campeonato Europeo de la WWF - Triple amenaza)', 'Kane vs. Kurt Angle', 'Steve Blackman vs. Al Snow (Campeonato Hardcore de la WWF)', 'The Hardy Boyz (Matt & Jeff Hardy) & Rikishi vs. T & A (Test & Albert) & Val Venis', 'Bull Buchanan vs. The Godfather', 'Triple H & Chris Benoit vs. The Rock & Chris Jericho'] },
      { date: '27', location: 'Worcester, MA', matches: ['Steve Blackman vs. X-Pac (Campeonato Hardcore de la WWF)', 'The Hardy Boyz (Matt & Jeff Hardy) vs. Lo Down (D’Lo Brown & Chaz)', 'Tazz vs. Grandmaster Sexay', 'The Dudley Boyz (Bubba Ray & D-Von Dudley) & Kane vs. Edge, Christian & Big Show (Tables Match)', 'Perry Saturn vs. Crash Holly (Campeonato Europeo de la WWF)', 'Chris Jericho & Lita vs. Chris Benoit & Trish Stratus', 'Kurt Angle vs. The Rock (Campeonato de la WWF)'] },
    ],
    ppvs: [
      { date: '23', name: 'Fully Loaded', location: 'Dallas, TX', description: 'The Rock retiene el título contra Chris Benoit. Triple H derrota a Chris Jericho en una brutal Last Man Standing match.', matches: ['Team Xtreme (Matt Hardy, Jeff Hardy & Lita) vs. T & A (Test & Albert) & Trish Stratus (Lucha mixta en equipo de seis personas)', 'Tazz vs. Al Snow', 'Eddie Guerrero © vs. Perry Saturn (Campeonato Europeo de la WWF)', 'Edge & Christian © vs. The Acolytes Protection Agency (Faarooq & Bradshaw) (Campeonatos en Parejas de la WWF)', 'Val Venis © vs. Rikishi (Campeonato Intercontinental de la WWF - Jaula de acero)', 'The Undertaker vs. Kurt Angle', {match: 'Last Man Standing: Triple H vs. Chris Jericho', rating: 4.6}, {match: 'The Rock © vs. Chris Benoit (Campeonato de la WWF; Si The Rock es descalificado, pierde el título)', rating: 4.5}], coverUrl: 'https://upload.wikimedia.org/wikipedia/en/c/c0/WWFFullyLoaded.jpg' },
    ],
  },
  {
    month: 'Agosto',
    monthId: 'august',
    year: 2000,
    raw: [
      { date: '7', location: 'East Rutherford, NJ', description: 'Se anuncia el evento principal de SummerSlam: The Rock vs. Triple H vs. Kurt Angle.', matches: ['WWF Championship: The Rock vs. Triple H', 'The Undertaker & Kane vs. Kurt Angle & Chris Benoit', 'WWF Intercontinental Championship: Chyna vs. Val Venis'] },
      { date: '14', location: 'Providence, RI', description: 'Triple H y Kurt Angle luchan por la atención de Stephanie.', matches: ['The Rock & Lita vs. Kurt Angle & Stephanie McMahon & Triple H', 'The Undertaker vs. Chris Benoit', 'WWF Tag Team Championship: Edge & Christian vs. The Dudley Boyz'] },
      { date: '21', location: 'Lafayette, LA', description: 'Último RAW antes de SummerSlam. Kurt Angle besa a Stephanie, enfureciendo a Triple H.', matches: ['The Rock vs. Shane McMahon', 'The Undertaker & Chris Jericho vs. Triple H & Kurt Angle', 'WWF Tag Team Championship: The Hardy Boyz vs. The Dudley Boyz'] },
      { date: '28', location: 'Greensboro, NC', description: 'The Rock celebra su victoria en SummerSlam. The Undertaker es el nuevo retador.', matches: ['WWF Championship: The Rock vs. Kane', 'The Undertaker vs. Chris Benoit', 'Eddie Guerrero vs. Kurt Angle'] },
    ],
    smackdown: [
      { date: '3', location: 'Birmingham, AL', matches: ['X-Pac (w/ Road Dogg) vs. Scotty 2 Hotty (w/ Grandmaster Sexay)', 'Eddie Guerrero & Rikishi (w/ Chyna) vs. Tazz & Val Venis (w/ Trish Stratus)', 'Matt Hardy vs. Edge (w/ Christian)', 'Chris Benoit & The Big Show (w/ Shane McMahon) vs. Kane & The Rock', 'Steve Blackman © vs. Perry Saturn (w/ Terri Runnels) (Campeonato Hardcore de la WWF)'] },
      { date: '10', location: 'East Rutherford, NJ', matches: ['Chris Jericho & Eddie Guerrero (w/ Chyna) vs. Chris Benoit (w/ Shane McMahon) & Val Venis (w/ Trish Stratus)', 'X-Pac vs. Rikishi', 'Al Snow (w/ Head) & The Kat vs. Perry Saturn & Terri Runnels (Lucha intergénero en parejas)', 'Edge & Christian © vs. The Dudley Boyz (Bubba Ray & D-Von Dudley) (Campeonatos en Parejas de la WWF)', 'Tazz vs. Crash Holly', 'Bull Buchanan & The Goodfather (w/ Steven Richards) vs. Too Cool (Scotty 2 Hotty & Grandmaster Sexay)', 'Steve Blackman © vs. Albert (w/ Trish Stratus) (Campeonato Hardcore de la WWF)', 'The Rock & The Undertaker vs. Triple H & Kurt Angle'] },
      { date: '17', location: 'Worcester, MA', matches: ['Rikishi & The Kat vs. Perry Saturn & Terri Runnels (Lucha intergénero)', 'Val Venis © (w/ Trish Stratus) vs. Eddie Guerrero (w/ Chyna) (Campeonato Intercontinental de la WWF)', 'The Acolytes (Bradshaw & Faarooq) & Crash Holly vs. The Big Boss Man & Kaientai (Taka Michinoku & Funaki)', 'Steve Blackman © vs. Chris Benoit (w/ Shane McMahon) (Campeonato Hardcore de la WWF)', 'Edge & Christian © vs. D-Von Dudley (w/ Bubba Ray Dudley) & Jeff Hardy (w/ Matt Hardy & Lita) (No por los títulos)', 'Too Cool (Scotty 2 Hotty & Grandmaster Sexay) vs. Road Dogg & X-Pac', 'The Rock © vs. Triple H (No por el título)'] },
      { date: '24', location: 'New Orleans, LA', matches: ['Rikishi vs. The Goodfather (w/ Bull Buchanan & Steven Richards)', 'Steve Blackman, Eddie Guerrero & Chyna vs. Val Venis, Test & Albert (w/ Trish Stratus)', 'The Undertaker vs. Road Dogg & X-Pac (Handicap)', 'Perry Saturn © (w/ Terri Runnels) vs. Al Snow (w/ Head) (Campeonato Europeo de la WWF)', 'The Hardy Boyz (Matt & Jeff Hardy) & Chris Jericho vs. Chris Benoit, Edge & Christian', 'The Rock & Lita vs. Kurt Angle & Stephanie McMahon-Helmsley'] },
      { date: '31', location: 'Fayetteville, NC', matches: ['Road Dogg vs. Bull Buchanan (w/ Steven Richards)', 'The Hardy Boyz (Matt & Jeff Hardy) & Lita vs. Jacqueline, Edge & Christian (Lucha intergénero en parejas)', 'Perry Saturn © (w/ Terri Runnels) vs. Al Snow (w/ Head) (Campeonato Europeo de la WWF)', 'The Undertaker vs. Chris Benoit (#1 Contender al Campeonato de la WWF)', 'Chris Jericho vs. Tazz', 'The Dudley Boyz (Bubba Ray & D-Von Dudley) vs. Kaientai (Taka Michinoku & Funaki)', 'Rikishi (w/ Mandy & Victoria) vs. Val Venis', 'Kurt Angle (w/ Stephanie McMahon-Helmsley) vs. Eddie Guerrero (w/ Chyna)'] },
    ],
    ppvs: [
      { date: '27', name: 'SummerSlam', location: 'Raleigh, NC', description: 'The Rock retiene el título después de que Triple H atacara a Kurt Angle. Edge & Christian ganan el primer TLC Match.', matches: ['Right to Censor (Steven Richards, Bull Buchanan & The Goodfather) vs. Too Cool (Scotty 2 Hotty, Grand Master Sexay & Rikishi) (Lucha en equipo de 6 hombres)', 'X-Pac vs. Road Dogg', 'Eddie Guerrero & Chyna vs. Val Venis © & Trish Stratus (Lucha intergénero en parejas por el Campeonato Intercontinental de la WWF)', 'Jerry Lawler vs. Tazz', 'Steve Blackman vs. Shane McMahon © (Campeonato Hardcore de la WWF - Lucha hardcore)', 'Chris Benoit vs. Chris Jericho (Best 2 out of 3 falls)', {match: 'Edge & Christian © vs. The Dudley Boyz (Bubba Ray Dudley & D-Von Dudley) vs. The Hardy Boyz (Matt Hardy & Jeff Hardy) (Campeonatos en Parejas de la WWF - Tables, Ladders, and Chairs)', rating: 4.8}, 'The Kat (w/ Al Snow) vs. Terri (w/ Perry Saturn) (Stinkface match)', 'The Undertaker vs. Kane', 'The Rock © vs. Triple H vs. Kurt Angle (Campeonato de la WWF - Triple amenaza)'], coverUrl: 'https://upload.wikimedia.org/wikipedia/en/1/15/SummerSlam2000poster.jpg' },
    ],
  },
  {
    month: 'Septiembre',
    monthId: 'september',
    year: 2000,
    raw: [
      { date: '4', location: 'Lexington, KY', description: 'Mick Foley investiga quién atropelló a Stone Cold en Survivor Series 99.', matches: ['The Rock & The Undertaker vs. Kurt Angle & Chris Benoit', 'WWF Tag Team Championship: Edge & Christian vs. The Hardy Boyz', 'Eddie Guerrero vs. Triple H'] },
      { date: '11', location: 'Kansas City, MO', description: 'The Rock se enfrenta a una serie de oponentes elegidos por sus rivales.', matches: ['WWF Championship: The Rock vs. Christian', 'The Undertaker vs. Kurt Angle', 'The Hardy Boyz vs. Kaientai'] },
      { date: '18', location: 'Chicago, IL', description: 'Se anuncia una lucha fatal de 4 esquinas para Unforgiven. Stone Cold regresa.', matches: ['WWF Championship: The Rock vs. The Undertaker vs. Chris Benoit vs. Kane', 'Triple H vs. T & A', 'The Hardy Boyz vs. Edge & Christian'] },
      { date: '25', location: 'State College, PA', description: 'La noche después de Unforgiven. The Rock celebra. Stone Cold busca venganza.', matches: ['WWF Championship: The Rock vs. Chris Benoit', {match: 'The Hardy Boyz vs. Edge & Christian: Ladder Match', rating: 4.7}, 'Triple H vs. Kurt Angle'] },
    ],
    smackdown: [
      { date: '7', location: 'Houston, TX', description: 'The Rock es puesto en luchas difíciles por Mick Foley.', matches: ['The Rock & The Hardy Boyz vs. Chris Benoit, Edge & Christian', 'The Undertaker vs. Triple H', 'Kane vs. Kurt Angle'] },
      { date: '14', location: 'Detroit, MI', description: 'La rivalidad entre The Rock y The Undertaker se calienta.', matches: ['WWF Championship: The Rock vs. Kane', 'The Undertaker vs. Chris Benoit', 'The Hardy Boyz vs. The Dudley Boyz'] },
      { date: '21', location: 'Milwaukee, WI', description: 'Stone Cold Steve Austin interroga a sospechosos sobre su accidente.', matches: ['The Rock vs. Chris Benoit & Kane', 'Triple H & Kurt Angle vs. The Acolytes', 'The Hardy Boyz vs. Edge & Christian'] },
    ],
    ppvs: [
      { date: '24', name: 'Unforgiven', location: 'Philadelphia, PA', description: 'The Rock retiene el Campeonato de la WWF contra Chris Benoit, Kane y The Undertaker. Stone Cold regresa y confronta a sus posibles atacantes.', matches: ['WWF Championship: The Rock vs. Chris Benoit vs. Kane vs. The Undertaker', 'Steel Cage Match for the WWF Tag Team Championship: The Hardy Boyz vs. Edge & Christian', 'WWF Intercontinental Championship: Eddie Guerrero vs. Rikishi', 'Hardcore Open Invitational: Steve Blackman wins'], coverUrl: 'https://upload.wikimedia.org/wikipedia/en/b/be/Unforgiven_2000.jpg' },
    ],
  },
  {
    month: 'Octubre',
    monthId: 'october',
    year: 2000,
    raw: [
      { date: '2', location: 'Boston, MA', description: 'Mick Foley continúa la investigación. Rikishi se revela como el conductor.', matches: ['The Hardy Boyz (Matt & Jeff Hardy) © vs. Too Cool (Scotty 2 Hotty & Grandmaster Sexay) (Campeonatos en Parejas de la WWF)', 'The Dudley Boyz (Bubba Ray & D-Von Dudley) & Chris Jericho vs. Tazz, Raven & X-Pac', 'The Rock & Rikishi vs. Chris Benoit & Kane', 'Steve Blackman © vs. Edge vs. Christian (Campeonato Hardcore de la WWF - Triple amenaza [Regla 24/7])', 'Eddie Guerrero & Chyna vs. Right to Censor (Steven Richards & Val Venis)', 'Kurt Angle vs. Triple H (#1 Contender al Campeonato de la WWF)'] },
      { date: '9', location: 'Washington, D.C.', description: 'Rikishi explica que lo hizo "por The Rock" y por la gente. Stone Cold lo ataca brutalmente.', matches: ['Lita © vs. Jacqueline (Campeonato Femenino de la WWF - Lucha hardcore)', 'Steve Blackman © vs. Raven (Campeonato Hardcore de la WWF [Regla 24/7])', 'Chris Benoit & X-Pac vs. Chris Jericho & Triple H', 'The Hardy Boyz (Matt & Jeff Hardy) © vs. Lo Down (Chaz & D’Lo Brown) (Campeonatos en Parejas de la WWF)', 'Al Snow © vs. Test (Campeonato Europeo de la WWF)', 'Right to Censor (Val Venis & The Godfather) vs. Eddie Guerrero & Chyna', 'The Rock & Rikishi vs. Kane & Kurt Angle'] },
      { date: '16', location: 'Detroit, MI', description: 'Se pacta The Rock vs. Kurt Angle y Stone Cold vs. Rikishi para No Mercy.', matches: ['Eddie Guerrero © vs. Chris Jericho (Campeonato Intercontinental de la WWF)', 'The APA (Bradshaw & Faarooq) vs. T & A (Test & Albert)', 'William Regal vs. Al Snow © (Campeonato Europeo de la WWF)', 'Triple H vs. Kane', 'X-Pac vs. Billy Gunn', 'Los Conquistadores (Edge & Christian) vs. The Dudley Boyz (Bubba Ray & D-Von Dudley)', 'Val Venis vs. Road Dogg', 'Kurt Angle, Edge & Christian vs. The Rock & The Hardy Boyz (Matt & Jeff Hardy)'] },
      { date: '23', location: 'Hartford, CT', description: 'La noche después de No Mercy. Kurt Angle es el nuevo campeón. Rikishi revela que Triple H estaba detrás de todo.', matches: ['Lita © vs. Trish Stratus (Campeonato Femenino de la WWF - Bra & Panties Match)', 'Chris Benoit vs. Road Dogg', 'Chris Jericho vs. William Regal © (Campeonato Europeo de la WWF)', 'Tazz & Raven vs. Too Cool (Scotty 2 Hotty & Grandmaster Sexay)', 'Billy Gunn vs. Val Venis', 'Los Conquistadores (Matt & Jeff Hardy) vs. Edge © (Campeonatos en Parejas de la WWF - Handicap 2 vs. 1)', 'Kurt Angle © vs. The Rock vs. Triple H (Campeonato de la WWF - Triple amenaza)'] },
      { date: '30', location: 'Worcester, MA', description: 'Stone Cold busca a Triple H. The Rock quiere su revancha contra Angle.', matches: ['Eddie Guerrero © vs. Chyna (Campeonato Intercontinental de la WWF)', 'Right to Censor (The Godfather, Bull Buchanan & Ivory) vs. Team Xtreme (The Hardy Boyz (Matt & Jeff Hardy) & Lita)', 'Test vs. Crash Holly (Lucha hardcore)', 'Stone Cold Steve Austin vs. Rikishi (Jaula de acero)', 'Steven Richards vs. Billy Gunn', 'Kurt Angle vs. Triple H', 'The Rock vs. Chris Jericho (#1 Contender al Campeonato de la WWF)'] },
    ],
    smackdown: [
      { date: '5', location: 'New York, NY', description: 'Stone Cold regresa oficialmente a SmackDown! y causa estragos.', matches: ['Lo Down (D’Lo Brown & Chaz) & Jacqueline vs. The Hardy Boyz (Matt & Jeff Hardy) & Lita', 'Al Snow © vs. X-Pac (Campeonato Europeo de la WWF)', 'Right to Censor (Bull Buchanan, The Godfather & Val Venis) vs. Eddie Guerrero & The APA (Bradshaw & Faarooq)', 'Tazz & Raven vs. The Dudley Boyz (Bubba Ray & D-Von Dudley)', 'Kurt Angle, Edge & Christian vs. Too Cool (Scotty 2 Hotty & Grandmaster Sexay) & Rikishi', 'Steve Blackman © vs. Albert (Campeonato Hardcore de la WWF)', 'Chris Benoit vs. Chris Jericho', 'Kane vs. The Rock © (Campeonato de la WWF)'] },
      { date: '12', location: 'Los Angeles, CA', description: 'Stone Cold sigue su cacería. The Rock y Kurt Angle en guerra.', matches: ['The Dudley Boyz (Bubba Ray & D-Von Dudley) vs. Lo Down (Lucha de mesas)', 'Eddie Guerrero © vs. Chris Jericho vs. X-Pac (Campeonato Intercontinental de la WWF - Triple amenaza)', 'Al Snow © vs. Albert (Campeonato Europeo de la WWF)', 'Triple H & Road Dogg vs. The Radicalz (Chris Benoit & Perry Saturn)', 'The Hardy Boyz (Matt & Jeff Hardy) © vs. Tazz & Raven (Campeonatos en Parejas de la WWF)', 'Kurt Angle vs. Kane', 'The Rock © vs. Val Venis (Campeonato de la WWF)'] },
      { date: '19', location: 'Meadowlands, NJ', description: 'Último show antes de No Mercy. Rikishi es arrestado después de atacar a Stone Cold con un coche.', matches: ['Battle Royal por #1 Contender a los Campeonatos en Parejas de la WWF: Los Conquistadores (Edge & Christian), The APA (Bradshaw & Faarooq), T & A (Test & Albert), Too Cool (Scotty 2 Hotty & Grandmaster Sexay), The Dudley Boyz (Bubba Ray & D-Von Dudley), Lo Down (D’Lo Brown & Chaz), Right to Censor (Bull Buchanan & The Godfather)', 'Steve Blackman © vs. Tazz (Campeonato Hardcore de la WWF)', 'William Regal © vs. Al Snow vs. Perry Saturn (Campeonato Europeo de la WWF - Triple amenaza)', 'Road Dogg vs. Raven', 'The Hardy Boyz (Matt & Jeff Hardy) & Chris Jericho vs. Edge, Christian & X-Pac', 'Lita © vs. Trish Stratus (Campeonato Femenino de la WWF)', 'Kurt Angle vs. The Rock vs. Triple H vs. Chris Benoit (Fatal 4-Way)'] },
      { date: '26', location: 'Hartford, CT', matches: ['The Hardy Boyz (Matt & Jeff Hardy) © vs. The Dudley Boyz (Bubba Ray & D-Von Dudley) (Campeonatos en Parejas de la WWF)', 'The Radicalz (Chris Benoit & Dean Malenko) vs. Triple H & Road Dogg', 'Chris Jericho vs. Kurt Angle © (Campeonato de la WWF)', 'Albert vs. Crash Holly (Lucha hardcore)', 'The Rock, Billy Gunn & Chyna vs. Right to Censor (The Godfather, Bull Buchanan & Val Venis)', 'Raven vs. Al Snow', 'Rikishi vs. Too Cool (Scotty 2 Hotty & Grandmaster Sexay) (Handicap 2 vs. 1)'] },
    ],
    ppvs: [
      { date: '22', name: 'No Mercy', location: 'Albany, NY', description: 'Kurt Angle derrota a The Rock para ganar el Campeonato de la WWF. Stone Cold vs. Rikishi termina en No Contest.', matches: ['Dudley Boyz Invitational Tables Match: The Dudley Boyz (Bubba Ray & D-Von Dudley) vs. The APA (Bradshaw & Faarooq) & Lita vs. T & A (Test & Albert) & Trish Stratus vs. Too Cool (Scotty 2 Hotty & Grandmaster Sexay) vs. Lo Down (D’Lo Brown & Chaz) vs. Right to Censor (Bull Buchanan & The Godfather)', 'The APA (Bradshaw & Faarooq) & Lita vs. T & A (Test & Albert) & Trish Stratus (Lucha mixta en equipo de seis personas)', 'Chris Jericho vs. X-Pac (Jaula de acero)', 'Right to Censor (Bull Buchanan & The Godfather) vs. Chyna & Billy Gunn (Lucha en parejas)', 'Stone Cold Steve Austin vs. Rikishi (No Holds Barred)', 'William Regal © vs. Naked Mideon (Campeonato Europeo de la WWF)', 'The Hardy Boyz (Matt & Jeff Hardy) © vs. Los Conquistadores (Uno & Dos) (Campeonatos en Parejas de la WWF)', 'Triple H vs. Chris Benoit', 'The Rock © vs. Kurt Angle (Campeonato de la WWF - No Disqualification)'], coverUrl: 'https://upload.wikimedia.org/wikipedia/en/4/4f/No_mercy_2000.jpg' },
    ],
  },
  {
    month: 'Noviembre',
    monthId: 'november',
    year: 2000,
    raw: [
      { date: '6', location: 'Houston, TX', description: 'Triple H admite haber orquestrado el ataque a Stone Cold. Se pacta la lucha para Survivor Series.', matches: ['The Rock & Stone Cold Steve Austin vs. Triple H & Rikishi', 'WWF Championship: Kurt Angle vs. Chris Jericho', 'The Hardy Boyz & Lita vs. The Radicalz'] },
      { date: '13', location: 'Columbus, OH', description: 'Triple H intenta atropellar a Stone Cold, pero era una trampa.', matches: ['WWF Championship: Kurt Angle vs. Crash Holly', 'The Rock vs. Chris Benoit', 'Stone Cold Steve Austin vs. Eddie Guerrero'] },
      { date: '20', location: 'Orlando, FL', description: 'La noche después de Survivor Series. Kurt Angle celebra. Stone Cold busca a Triple H.', matches: ['WWF Championship: Kurt Angle vs. The Rock', 'Stone Cold Steve Austin vs. Chris Benoit', 'The Hardy Boyz vs. The Radicalz'] },
      { date: '27', location: 'Ames, IA', description: 'Se anuncia una lucha Hell in a Cell de 6 hombres para Armageddon.', matches: ['WWF Championship: Kurt Angle vs. Rikishi', 'The Rock & The Undertaker vs. Edge & Christian', 'Stone Cold Steve Austin vs. William Regal'] },
    ],
    smackdown: [
      { date: '2', location: 'Rochester, NY', description: 'The Rock y Stone Cold se unen contra el enemigo común.', matches: ['WWF Championship: The Rock vs. Kurt Angle', 'Stone Cold Steve Austin vs. Rikishi', 'The Hardy Boyz vs. Bull Buchanan & The Goodfather'] },
      { date: '9', location: 'Pittsburgh, PA', description: 'The Radicalz se reúnen y atacan a DX.', matches: ['The Rock & Chris Jericho vs. Kurt Angle & Kane', 'Stone Cold Steve Austin vs. The Undertaker', 'The Hardy Boyz vs. The Dudley Boyz'] },
      { date: '16', location: 'Sunrise, FL', description: 'Último show antes de Survivor Series. Caos total entre todas las facciones.', matches: ['The Rock, Stone Cold, The Undertaker & Chris Jericho vs. Kurt Angle, Triple H, Edge & Christian & Rikishi', 'WWF Tag Team Championship: Bull Buchanan & The Goodfather vs. The Hardy Boyz', 'Val Venis vs. Billy Gunn'] },
    ],
    ppvs: [
      { date: '19', name: 'Survivor Series', location: 'Tampa, FL', description: 'Stone Cold deja caer a Triple H desde una grúa dentro de un coche. Kurt Angle retiene el título contra The Undertaker.', matches: ['No Disqualification Match: Stone Cold Steve Austin vs. Triple H', 'WWF Championship: Kurt Angle vs. The Undertaker', 'Survivor Series Elimination Match: The Radicalz vs. DX & K-Kwik', 'Survivor Series Elimination Match: The Rock, Chris Jericho, Kane & The Undertaker vs. Kurt Angle, Edge, Christian & Rikishi'], coverUrl: 'https://upload.wikimedia.org/wikipedia/en/3/3e/SS_00.jpg' },
    ],
  },
  {
    month: 'Diciembre',
    monthId: 'december',
    year: 2000,
    raw: [
      { date: '4', location: 'East Rutherford, NJ', description: 'Vince McMahon intenta cancelar el Hell in a Cell, pero Mick Foley se lo impide.', matches: ['Rikishi vs. The Undertaker', 'Right to Censor (Bull Buchanan & The Godfather) © vs. The Hardy Boyz (Matt & Jeff Hardy) (Campeonatos en Parejas de la WWF)', 'Chris Benoit vs. Hardcore Holly', 'Edge & Christian vs. Road Dogg & K-Kwik', 'Kurt Angle © vs. Chris Jericho (Campeonato de la WWF)', 'Billy Gunn © vs. Val Venis (Campeonato Intercontinental de la WWF)', 'Dean Malenko © vs. Lita (Campeonato Ligero de la WWF; Si Malenko gana, obtiene una cita con Lita)', 'William Regal vs. Crash Holly (Campeonato Europeo de la WWF)'] },
      { date: '11', location: 'Little Rock, AR', description: 'La noche después de Armageddon. Kurt Angle sigue siendo campeón. Vince McMahon se divorcia de Linda en el ring.', matches: ['The Radicalz (Dean Malenko & Perry Saturn) vs. The Hardy Boyz (Matt & Jeff Hardy)', 'Billy Gunn © vs. Chris Benoit (Campeonato Intercontinental de la WWF)', 'The Rock & The Dudley Boyz (Bubba Ray & D-Von Dudley) vs. Kurt Angle, Edge & Christian (Lucha de mesas)', 'Chyna vs. Ivory', 'The APA (Bradshaw & Faarooq) vs. T & A (Test & Albert)', 'Jerry Lawler, Road Dogg & K-Kwik vs. Right to Censor (Steven Richards, Bull Buchanan & The Godfather)', 'Raven vs. Al Snow (Lucha hardcore)'] },
      { date: '18', location: 'Richmond, VA', description: 'Vince McMahon inicia un romance público con Trish Stratus.', matches: ['Chris Benoit © vs. Jeff Hardy (Campeonato Intercontinental de la WWF)', 'Right to Censor (Val Venis, Bull Buchanan & The Godfather) vs. The Dudley Boyz (Bubba Ray & D-Von Dudley) & Billy Gunn', 'The Rock & The Undertaker vs. Edge & Christian © (Campeonatos en Parejas de la WWF)', 'Chris Jericho vs. Perry Saturn', 'William Regal vs. Stone Cold Steve Austin', 'The APA (Bradshaw & Faarooq) & Jacqueline vs. T & A (Test & Albert) & Trish Stratus', 'Kurt Angle © vs. Vince McMahon (Campeonato de la WWF)'] },
      { date: '25', location: 'Chattanooga, TN', description: 'Show de Navidad. The Rock se disfraza de Santa Claus para burlarse de Kurt Angle.', matches: ['The Hardy Boyz (Matt & Jeff Hardy) vs. The Radicalz (Chris Benoit & Dean Malenko)', 'Steve Blackman © vs. Raven vs. Hardcore Holly (Campeonato Hardcore de la WWF - Triple amenaza)', 'Raven vs. Steve Blackman (Campeonato Hardcore de la WWF)', 'Stone Cold Steve Austin vs. Kane', 'Too Cool (Scotty 2 Hotty & Grandmaster Sexay) vs. T & A (Test & Albert)', 'Kurt Angle, Edge & Christian vs. Chris Jericho & The Dudley Boyz (Bubba Ray & D-Von Dudley)', 'Right to Censor (Bull Buchanan & The Godfather) vs. The APA (Bradshaw & Faarooq)', 'The Rock vs. The Undertaker'] },
    ],
    smackdown: [
      { date: '7', location: 'New Orleans, LA', description: 'Los 6 participantes del Hell in a Cell luchan entre sí en diferentes combinaciones.', matches: ['Val Venis & Ivory vs. Billy Gunn & Chyna', 'Molly Holly vs. Trish Stratus', 'Chris Jericho & Hardcore Holly vs. William Regal & Kane', 'K-Kwik & Road Dogg vs. Edge & Christian', 'Kurt Angle © vs. The Undertaker vs. The Rock vs. Stone Cold Steve Austin (Campeonato de la WWF - Fatal 4-Way)'] },
      { date: '14', location: 'Birmingham, AL', description: 'Vince McMahon se convierte en una figura autoritaria tiránica.', matches: ['Edge & Christian vs. The Dudley Boyz (Bubba Ray & D-Von Dudley)', 'Ivory © vs. Lita (Campeonato Femenino de la WWF)', 'Val Venis vs. Billy Gunn', 'The Undertaker vs. Raven (Lucha hardcore)', 'The Hardy Boyz (Matt & Jeff Hardy) vs. The Radicalz (Chris Benoit & Perry Saturn)', 'Dean Malenko vs. Chris Jericho', 'The Rock & Stone Cold Steve Austin vs. Kurt Angle & William Regal'] },
      { date: '21', location: 'Charlotte, NC', description: 'Construcción para Royal Rumble 2001. Se anuncian los primeros participantes.', matches: ['The Dudley Boyz (Bubba Ray & D-Von Dudley) vs. Lo Down (D’Lo Brown & Chaz)', 'Ivory © vs. Jacqueline (Campeonato Femenino de la WWF)', 'Chris Jericho & The Hardy Boyz (Matt & Jeff Hardy) vs. The Radicalz (Chris Benoit, Dean Malenko & Perry Saturn)', 'William Regal © vs. Hardcore Holly (Campeonato Europeo de la WWF)', 'Crash Holly & Molly Holly vs. Taka Michinoku & Funaki', 'Steve Blackman © vs. Raven (Campeonato Hardcore de la WWF)', 'Billy Gunn vs. Steven Richards', 'Edge & Christian vs. The Rock & The Undertaker © (Campeonatos en Parejas de la WWF; Árbitro especial: Kurt Angle)'] },
      { date: '28', location: 'Birmingham, AL', matches: ['Edge & Christian vs. Chris Jericho (Handicap 2 vs. 1)', 'Chris Benoit © vs. Matt Hardy (Campeonato Intercontinental de la WWF)', 'Kurt Angle © vs. Bubba Ray Dudley (Campeonato de la WWF)', 'Right to Censor (Bull Buchanan & The Godfather) vs. The APA (Bradshaw & Faarooq)', 'Raven © vs. Jeff Hardy (Campeonato Hardcore de la WWF)', 'T & A (Test & Albert) vs. Too Cool (Scotty 2 Hotty & Grandmaster Sexay)', 'The Rock & The Undertaker vs. William Regal, Rikishi & Kane (Handicap 3 vs. 2)'] },
    ],
    ppvs: [
      { date: '10', name: 'Armageddon', location: 'Birmingham, AL', description: 'Kurt Angle retiene el título en una caótica lucha Hell in a Cell de 6 hombres. The Radicalz se establecen como una facción dominante.', matches: ['Scotty 2 Hotty (w/ Grand Master Sexay) vs. D\'Lo Brown (w/ Chaz y Tiger Ali Singh) (Lucha individual)', 'The Radicalz (Dean Malenko, Eddie Guerrero y Perry Saturn) (w/ Terri) vs. Team Xtreme (Jeff Hardy, Matt Hardy y Lita) (Lucha en equipo de eliminación intergénero)', 'William Regal © vs. Hardcore Holly (Campeonato Europeo de la WWF)', 'Val Venis (w/ Ivory) vs. Chyna (Lucha individual)', 'Chris Jericho vs. Kane (Last Man Standing)', 'Edge y Christian vs. The Dudley Boyz (Bubba Ray Dudley y D-Von Dudley) vs. K-Kwik y Road Dogg vs. Right to Censor (Bull Buchanan y The Goodfather) © (w/ Steven Richards) (Campeonatos en Parejas de la WWF - Fatal 4-Way)', 'Billy Gunn © vs. Chris Benoit (Campeonato Intercontinental de la WWF)', 'Ivory © vs. Molly Holly vs. Trish Stratus (Campeonato Femenino de la WWF - Triple amenaza)', {match: '6-Man Hell in a Cell for WWF Championship: Kurt Angle vs. The Rock vs. Stone Cold Steve Austin vs. Triple H vs. The Undertaker vs. Rikishi', rating: 4.5}], coverUrl: 'https://upload.wikimedia.org/wikipedia/en/e/e9/Armageddon00.jpg' },
    ],
  },
  {
    month: 'Enero',
    monthId: 'january',
    year: 2001,
    raw: [
        { date: '1', location: 'Austin, TX', description: 'El camino a Royal Rumble comienza. Stone Cold Steve Austin y The Rock se declaran para el Rumble Match.', matches: ['WWF Championship: Kurt Angle vs. Kane', 'The Rock vs. The Undertaker', 'Stone Cold Steve Austin vs. William Regal'] },
        { date: '8', location: 'San Jose, CA', description: 'Vince McMahon introduce la regla "No Contact" entre Stone Cold y Triple H.', matches: ['The Rock & Undertaker vs. Kane & Rikishi', 'WWF Tag Team Championship: The Dudley Boyz vs. Edge & Christian', 'Chris Jericho vs. Chris Benoit'] },
        { date: '15', location: 'Chicago, IL', description: 'Drew Carey aparece en RAW y Vince McMahon lo convence de entrar al Royal Rumble.', matches: ['WWF Championship: Kurt Angle vs. Stone Cold Steve Austin', 'The Rock vs. The Hardy Boyz', 'The Undertaker vs. Rikishi'] },
        { date: '22', location: 'Lafayette, LA', description: 'La noche después del Rumble. Triple H ataca brutalmente a Stone Cold después de que Austin ganara el Rumble.', matches: ['WWF Championship: Kurt Angle vs. The Rock', 'Stone Cold Steve Austin & Triple H vs. Kane & Rikishi', 'Chris Jericho vs. Chris Benoit'] },
        { date: '29', location: 'Baltimore, MD', description: 'Se anuncia The Rock vs. Kurt Angle para No Way Out. Stephanie McMahon es nombrada la nueva dueña de ECW (en storyline).', matches: ['The Rock vs. Kurt Angle', 'WWF Tag Team Championship Tables Match: The Dudley Boyz vs. The Hardy Boyz', 'Stone Cold Steve Austin vs. Test'] },
    ],
    smackdown: [
        { date: '4', location: 'Houston, TX', description: 'Mr. McMahon anuncia que el WWF Championship será defendido contra The Rock en Royal Rumble.', matches: ['#1 Contender Match for WWF Championship: The Rock vs. Kane', 'The Dudley Boyz vs. Bull Buchanan & The Goodfather', 'Chris Jericho vs. Kurt Angle'] },
        { date: '11', location: 'New York, NY', description: 'Lucha de mesas entre The Dudleyz y Edge & Christian.', matches: ['Tables Match: The Dudley Boyz vs. Edge & Christian', 'The Rock vs. The APA', 'Stone Cold Steve Austin vs. Kurt Angle'] },
        { date: '18', location: 'Mobile, AL', description: 'Último show antes del Royal Rumble. Confrontación masiva entre los participantes del Rumble.', matches: ['The Rock & Stone Cold Steve Austin vs. Kurt Angle, Kane & Rikishi', 'WWF Intercontinental Championship: Chris Jericho vs. Tazz', 'The Undertaker vs. The Dudley Boyz'] },
        { date: '25', location: 'Washington, D.C.', description: 'Stone Cold, el ganador del Rumble, busca su camino a WrestleMania. Triple H emerge como un obstáculo.', matches: ['WWF Championship: Kurt Angle vs. Kane', 'The Rock vs. Chris Benoit', 'The Hardy Boyz vs. The APA'] },
    ],
    ppvs: [
        { date: '21', name: 'Royal Rumble', location: 'New Orleans, LA', description: 'Stone Cold Steve Austin gana el Royal Rumble Match por tercera vez. Kurt Angle retiene el título contra Triple H.', matches: [{match: '30-Man Royal Rumble Match', rating: 4.2}, 'WWF Championship: Kurt Angle vs. Triple H', {match: 'Ladder Match for the WWF Intercontinental Championship: Chris Jericho vs. Chris Benoit', rating: 4.9}, 'WWF Tag Team Championship: The Dudley Boyz vs. Edge & Christian'], coverUrl: 'https://upload.wikimedia.org/wikipedia/en/0/04/Royal_Rumble_2001.jpg' },
    ],
  },
];

